language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            #- llvm-toolchain-trusty-7
        packages:
            - gcc-8
            - g++-8
            #- clang-7
            #- libllvm7
            #- llvm-7
            #- llvm-7-dev
            #- llvm-7-runtime
            - libedit-dev
notifications:
  email: false

cache:
  directories:
    deps

install:
    - timeout 1800 ./get-deps.sh || true

before_script:
# - mkdir build
# - cd build
# - cmake -DCMAKE_CXX_COMPILER=$(which g++-8) -DCMAKE_C_COMPILER=$(which gcc-8) -DCMAKE_PREFIX_PATH=/usr/local/lib/cmake/llvm ..

script: 
#  - make -j2
