language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8
            - cmake-3.11

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j2
