language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
        packages:
            - gcc-8
            - g++-8
              #- clang-7
            - libllvm7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime

notifications:
  email: false

before_script:
  - sudo rm -rf /usr/local/clang-5.0.0/
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$(which g++-8) -DCMAKE_C_COMPILER=$(which gcc-8) -DLLVM_INSTALL_PREFIX=/usr/lib/llvm-7/ ..

script: 
  - make -j2
