language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8

notifications:
  email: false

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$(which g++-8) -DCMAKE_C_COMPILER=$(which gcc-8) ..

script: 
  - make -j2
