language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            #- llvm-toolchain-trusty-7
        packages:
            - gcc-8
            - g++-8
            #- libedit-dev
notifications:
  email: false

cache:
  directories:
    deps

install:
    - ./get-deps.sh
    - sudo cp -r deps/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/* /usr/local

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$(which g++-8) -DCMAKE_C_COMPILER=$(which gcc-8) ..

script: 
  - make -j2
