language: cpp
compiler: gcc
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8
    env:
    - COMPILER_EVAL="export CC=gcc-8 && export CXX=g++-8"

notifications:
  email: false

before_script:
  - eval "${COMPILER_EVAL}"
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j2
